import pytest


def test_invalid:
with pytest.raise(Exception):
